# íŒŒì¼ ê²½ë¡œ: /root/test-gitops-repo/manifests/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-hello-app
  labels:
    app: hello-world
spec:
  imagePullSecrets:       # <--- ì´ ë¶€ë¶„ì„ ì¶”ê°€í•©ë‹ˆë‹¤!
  - name: harbor-registry-secret # <--- ì´ ë¶€ë¶„ì„ ì¶”ê°€í•©ë‹ˆë‹¤!
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: webserver
        # ğŸ’¡ ì¤‘ìš”: Harbor ì£¼ì†Œ ë° í”„ë¡œì íŠ¸/ì´ë¯¸ì§€ ì´ë¦„
        # Jenkinsê°€ ì´ íŒŒì¼ì˜ íƒœê·¸ë¥¼ ë³€ê²½í•˜ê²Œ ë©ë‹ˆë‹¤.
        image: 172.16.8.200:30003/test/test:v1.0
        ports:
        - containerPort: 8080
