# /root/test-gitops-repo/manifests/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-hello-app
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      # í”„ë¼ì´ë¹— ë ˆì§€ìŠ¤íŠ¸ë¦¬ ì¸ì¦ ì •ë³´ ì‚¬ìš©
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - name: webserver
        # ğŸ’¡ ì¤‘ìš”: Harbor ì£¼ì†Œ ë° í”„ë¡œì íŠ¸/ì´ë¯¸ì§€ ì´ë¦„
        image: 172.16.8.200:30003/test/test:v1.0
        ports:
        - containerPort: 8080
